/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: surveytown (https://sketchfab.com/surveytown)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/boeing-d7592c496b3f4245a34b3200d95001c3
title: Boeing
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/plane.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
            <group position={[-3.99, 65.64, -90.75]} rotation={[Math.PI / 2, 0, 0]} scale={41.74}>
              <group position={[0, 4.53, 14.01]}>
                <mesh geometry={nodes.Object_7.geometry} material={materials.VMtl145} />
              </group>
              <group position={[0, 7.81, -21.68]}>
                <mesh geometry={nodes.Object_10.geometry} material={materials.VMtl145_0} />
              </group>
              <group position={[0, 7.81, -23.06]}>
                <mesh geometry={nodes.Object_13.geometry} material={materials.VMtl145_1} />
              </group>
              <group position={[0, 3.12, -7.53]}>
                <mesh geometry={nodes.Object_16.geometry} material={materials.VMtl145_2} />
              </group>
              <group position={[0, 3.18, -4.4]}>
                <mesh geometry={nodes.Object_19.geometry} material={materials.VMtl145_3} />
              </group>
              <group position={[0, 1.12, 16.55]}>
                <mesh geometry={nodes.Object_22.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[0, 0.69, 16.52]}>
                <mesh geometry={nodes.Object_25.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[0, 0.49, 16.55]}>
                <mesh geometry={nodes.Object_28.geometry} material={materials.VMtl145_5} />
              </group>
              <group position={[0, 1.4, 16.16]}>
                <mesh geometry={nodes.Object_31.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[0, 1.4, 16.16]}>
                <mesh geometry={nodes.Object_34.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[0, 1.61, 16.16]}>
                <mesh geometry={nodes.Object_37.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[0, 1.67, 16.55]}>
                <mesh geometry={nodes.Object_40.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[0, 1.4, 16.72]}>
                <mesh geometry={nodes.Object_43.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[0, 1.4, 16.72]}>
                <mesh geometry={nodes.Object_46.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[0, 1.67, 16.55]}>
                <mesh geometry={nodes.Object_49.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[0, 1.85, 16.67]}>
                <mesh geometry={nodes.Object_52.geometry} material={materials.VMtl145_6} />
                <mesh geometry={nodes.Object_54.geometry} material={materials.VMtl017} />
              </group>
              <group position={[0.64, 2.04, 16.89]}>
                <mesh geometry={nodes.Object_57.geometry} material={materials.VMtl145_7} />
              </group>
              <group position={[0, 3.28, -13.29]}>
                <mesh geometry={nodes.Object_60.geometry} material={materials.VMtl145_8} />
              </group>
              <group position={[0, 4.96, -21.61]}>
                <mesh geometry={nodes.Object_63.geometry} material={materials.VMtl145_9} />
              </group>
              <group position={[0, 7.81, -23.06]}>
                <mesh geometry={nodes.Object_66.geometry} material={materials.VMtl145_1} />
              </group>
              <group position={[0, 4.96, -21.61]}>
                <mesh geometry={nodes.Object_69.geometry} material={materials.VMtl145_9} />
              </group>
              <group position={[0, 3.18, -4.4]}>
                <mesh geometry={nodes.Object_72.geometry} material={materials.VMtl145_3} />
              </group>
              <group position={[0, 2.04, 16.89]}>
                <mesh geometry={nodes.Object_75.geometry} material={materials.VMtl145_10} />
              </group>
              <group position={[4.6, 3.16, -3.06]}>
                <mesh geometry={nodes.Object_78.geometry} material={materials.VMtl145_11} />
              </group>
              <group position={[4.54, 2.95, -2.63]}>
                <mesh geometry={nodes.Object_81.geometry} material={materials.VMtl145_12} />
              </group>
              <group position={[0, 2.95, -2.63]}>
                <mesh geometry={nodes.Object_84.geometry} material={materials.VMtl145_12} />
              </group>
              <group position={[0, 3.16, -3.06]}>
                <mesh geometry={nodes.Object_87.geometry} material={materials.VMtl145_11} />
              </group>
              <group position={[-0.33, 0.69, 16.52]}>
                <mesh geometry={nodes.Object_90.geometry} material={materials.VMtl145_13} />
              </group>
              <group position={[-0.21, 0.69, 16.52]}>
                <mesh geometry={nodes.Object_93.geometry} material={materials.VMtl145_14} />
              </group>
              <group position={[0.44, 0.69, 16.52]}>
                <mesh geometry={nodes.Object_96.geometry} material={materials.VMtl145_14} />
              </group>
              <group position={[0.33, 0.69, 16.52]}>
                <mesh geometry={nodes.Object_99.geometry} material={materials.VMtl145_13} />
              </group>
              <group position={[-4.21, 3.18, -3.14]}>
                <mesh geometry={nodes.Object_102.geometry} material={materials.VMtl145_4} />
                <mesh geometry={nodes.Object_104.geometry} material={materials.VMtl145_5} />
              </group>
              <group position={[-3.97, 1.46, -2.99]}>
                <mesh geometry={nodes.Object_107.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[-4.78, 0.55, -3.77]}>
                <mesh geometry={nodes.Object_110.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[-2.82, 2.88, -2.22]}>
                <mesh geometry={nodes.Object_113.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[-3.39, 2.34, -2.6]}>
                <mesh geometry={nodes.Object_116.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[-3.39, 2.34, -3.17]}>
                <mesh geometry={nodes.Object_119.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[-3.39, 2.34, -2.6]}>
                <mesh geometry={nodes.Object_122.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[-2.64, 2.83, -3.16]}>
                <mesh geometry={nodes.Object_125.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[-3.3, 2.3, -3.16]}>
                <mesh geometry={nodes.Object_128.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[-3.97, 1.46, -3.16]}>
                <mesh geometry={nodes.Object_131.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[-2.78, 2.87, -2.28]}>
                <mesh geometry={nodes.Object_134.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[-2.63, 2.83, -3.23]}>
                <mesh geometry={nodes.Object_137.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[-3.55, 3.1, -2.81]}>
                <mesh geometry={nodes.Object_140.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[-4.04, 2.5, -3.26]}>
                <mesh geometry={nodes.Object_143.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[-3.31, 2.3, -3.25]}>
                <mesh geometry={nodes.Object_146.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[-3.34, 2.32, -2.67]}>
                <mesh geometry={nodes.Object_149.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[-3.96, 1.77, -3.25]}>
                <mesh geometry={nodes.Object_152.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[-3.89, 1.8, -3.03]}>
                <mesh geometry={nodes.Object_155.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[-4.93, 0.55, -2.5]}>
                <mesh geometry={nodes.Object_158.geometry} material={materials.VMtl145_14} />
              </group>
              <group position={[-3.78, 0.55, -3.77]}>
                <mesh geometry={nodes.Object_161.geometry} material={materials.VMtl145_14} />
              </group>
              <group position={[-3.63, 0.55, -2.5]}>
                <mesh geometry={nodes.Object_164.geometry} material={materials.VMtl145_13} />
              </group>
              <group position={[-3.78, 0.55, -2.5]}>
                <mesh geometry={nodes.Object_167.geometry} material={materials.VMtl145_14} />
              </group>
              <group position={[-3.63, 0.55, -3.77]}>
                <mesh geometry={nodes.Object_170.geometry} material={materials.VMtl145_13} />
              </group>
              <group position={[-4.78, 0.55, -2.5]}>
                <mesh geometry={nodes.Object_173.geometry} material={materials.VMtl145_13} />
              </group>
              <group position={[-4.93, 0.55, -3.77]}>
                <mesh geometry={nodes.Object_176.geometry} material={materials.VMtl145_14} />
              </group>
              <group position={[-4.78, 0.55, -3.77]}>
                <mesh geometry={nodes.Object_179.geometry} material={materials.VMtl145_13} />
              </group>
              <group position={[3.97, 1.46, -2.99]}>
                <mesh geometry={nodes.Object_182.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[4.78, 0.55, -3.77]}>
                <mesh geometry={nodes.Object_185.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[2.82, 2.88, -2.22]}>
                <mesh geometry={nodes.Object_188.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[3.39, 2.34, -2.6]}>
                <mesh geometry={nodes.Object_191.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[3.39, 2.34, -3.17]}>
                <mesh geometry={nodes.Object_194.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[3.39, 2.34, -2.6]}>
                <mesh geometry={nodes.Object_197.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[4.21, 3.18, -3.14]}>
                <mesh geometry={nodes.Object_200.geometry} material={materials.VMtl145_4} />
                <mesh geometry={nodes.Object_202.geometry} material={materials.VMtl145_5} />
              </group>
              <group position={[2.64, 2.83, -3.16]}>
                <mesh geometry={nodes.Object_205.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[3.3, 2.3, -3.16]}>
                <mesh geometry={nodes.Object_208.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[3.97, 1.46, -3.16]}>
                <mesh geometry={nodes.Object_211.geometry} material={materials.VMtl145_4} />
              </group>
              <group position={[2.78, 2.87, -2.28]}>
                <mesh geometry={nodes.Object_214.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[2.63, 2.83, -3.23]}>
                <mesh geometry={nodes.Object_217.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[3.55, 3.1, -2.81]}>
                <mesh geometry={nodes.Object_220.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[4.04, 2.5, -3.26]}>
                <mesh geometry={nodes.Object_223.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[3.31, 2.3, -3.25]}>
                <mesh geometry={nodes.Object_226.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[3.34, 2.32, -2.67]}>
                <mesh geometry={nodes.Object_229.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[3.96, 1.77, -3.25]}>
                <mesh geometry={nodes.Object_232.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[3.89, 1.8, -3.03]}>
                <mesh geometry={nodes.Object_235.geometry} material={materials.VMtl145_6} />
              </group>
              <group position={[4.93, 0.55, -2.5]}>
                <mesh geometry={nodes.Object_238.geometry} material={materials.VMtl145_14} />
              </group>
              <group position={[3.78, 0.55, -3.77]}>
                <mesh geometry={nodes.Object_241.geometry} material={materials.VMtl145_14} />
              </group>
              <group position={[3.63, 0.55, -2.5]}>
                <mesh geometry={nodes.Object_244.geometry} material={materials.VMtl145_13} />
              </group>
              <group position={[3.78, 0.55, -2.5]}>
                <mesh geometry={nodes.Object_247.geometry} material={materials.VMtl145_14} />
              </group>
              <group position={[3.63, 0.55, -3.77]}>
                <mesh geometry={nodes.Object_250.geometry} material={materials.VMtl145_13} />
              </group>
              <group position={[4.78, 0.55, -2.5]}>
                <mesh geometry={nodes.Object_253.geometry} material={materials.VMtl145_13} />
              </group>
              <group position={[4.93, 0.55, -3.77]}>
                <mesh geometry={nodes.Object_256.geometry} material={materials.VMtl145_14} />
              </group>
              <group position={[4.78, 0.55, -3.77]}>
                <mesh geometry={nodes.Object_259.geometry} material={materials.VMtl145_13} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_262.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 5.01]}>
                <mesh geometry={nodes.Object_265.geometry} material={materials.VMtl145_16} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_268.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_271.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_274.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_277.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_280.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_283.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_286.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_289.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_292.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_295.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_298.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_301.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_304.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_307.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_310.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_313.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.54, 2.3, 0.76]}>
                <mesh geometry={nodes.Object_316.geometry} material={materials.VMtl145_17} />
              </group>
              <group position={[8.54, 2.3, 0.41]}>
                <mesh geometry={nodes.Object_319.geometry} material={materials.VMtl145_6} />
                <mesh geometry={nodes.Object_321.geometry} material={materials.VMtl121} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_324.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_327.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_330.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_333.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[8.54, 2.3, -0.89]}>
                <mesh geometry={nodes.Object_336.geometry} material={materials.VMtl145_18} />
              </group>
              <group position={[8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_339.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[7.23, 3.3, 3.69]}>
                <mesh geometry={nodes.Object_342.geometry} material={materials.VMtl145_5} />
              </group>
              <group position={[8.53, 2.38, 3.32]}>
                <mesh geometry={nodes.Object_345.geometry} material={materials.VMtl145_19} />
              </group>
              <group position={[8.54, 0.59, 3.09]}>
                <mesh geometry={nodes.Object_348.geometry} material={materials.VMtl116} />
              </group>
              <group position={[8.53, 4.71, -0.6]}>
                <mesh geometry={nodes.Object_351.geometry} material={materials.VMtl145_20} />
              </group>
              <group position={[0, 4.71, -0.6]}>
                <mesh geometry={nodes.Object_354.geometry} material={materials.VMtl145_20} />
              </group>
              <group position={[-8.54, 2.3, 0.76]}>
                <mesh geometry={nodes.Object_357.geometry} material={materials.VMtl145_17} />
              </group>
              <group position={[-8.54, 2.3, 0.41]}>
                <mesh geometry={nodes.Object_360.geometry} material={materials.VMtl145_6} />
                <mesh geometry={nodes.Object_362.geometry} material={materials.VMtl121} />
              </group>
              <group position={[-8.54, 2.3, -0.89]}>
                <mesh geometry={nodes.Object_365.geometry} material={materials.VMtl145_18} />
              </group>
              <group position={[-8.54, 0.59, 3.09]}>
                <mesh geometry={nodes.Object_368.geometry} material={materials.VMtl116} />
              </group>
              <group position={[0, 2.38, 3.32]}>
                <mesh geometry={nodes.Object_371.geometry} material={materials.VMtl145_21} />
              </group>
              <group position={[-7.23, 3.3, 3.69]}>
                <mesh geometry={nodes.Object_374.geometry} material={materials.VMtl145_5} />
              </group>
              <group position={[0, 3.12, -7.53]}>
                <mesh geometry={nodes.Object_377.geometry} material={materials.VMtl145_2} />
              </group>
              <group position={[2.21, 1.87, 5.09]}>
                <mesh geometry={nodes.Object_380.geometry} material={materials.VMtl145_22} />
              </group>
              <group position={[0, 1.87, 5.09]}>
                <mesh geometry={nodes.Object_383.geometry} material={materials.VMtl145_22} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_386.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 5.01]}>
                <mesh geometry={nodes.Object_389.geometry} material={materials.VMtl145_16} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_392.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_395.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_398.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_401.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_404.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_407.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_410.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_413.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_416.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_419.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_422.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_425.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_428.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_431.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_434.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_437.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_440.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_443.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_446.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_449.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[-8.53, 2.39, 4.98]}>
                <mesh geometry={nodes.Object_452.geometry} material={materials.VMtl145_15} />
              </group>
              <group position={[0, 3.28, -13.29]}>
                <mesh geometry={nodes.Object_455.geometry} material={materials.VMtl145_8} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/plane.gltf')
